#!/usr/bin/env bash
# DO NOT EDIT — generated by generate_distro_package_setup_code.sh
# Configuring packages for a Linux system
set -uo pipefail

dotdir="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
source "$dotdir/setup/setup_functions.sh"

log_info "Configuring packages for Linux (Debian and derivative distros) ..."

log_info "Upgrading existing packages."
sudo apt-get update -y --fix-missing -qq && sudo apt-get upgrade -y -qq

log_info "Installing packages."

# Packages (distro-agnostic):

# Common
install_apt_package bat # cat replacement with syntax highlighting, git integration
install_apt_package cifs-utils # Common Internet File System utilities
install_apt_package curl # command line tool for transferring data with URL syntax
install_apt_package eza # Modern replacement for ls
install_apt_package git # fast, scalable, distributed revision control system
install_apt_package grc # Colorize logfiles and command output
install_apt_package hexyl # Terminal hex viewer
install_apt_package jq # lightweight and flexible command-line JSON processor
install_apt_package lnav # ncurses-based log file viewer
install_apt_package mosh # Mobile shell that supports roaming and intelligent local echo
install_apt_package mtr # traceroute and ping in a single tool
install_apt_package ncdu # NCurses Disk Usage
install_apt_package ngrep # grep for network traffic
install_apt_package ranger # caca-utils highlight atool w3m poppler-utils mediainfo # File manager with an ncurses frontend written in Python
install_apt_package ripgrep # Fast regex text searching tool for files (recursively), respects .gitignore
install_apt_package rlwrap # readline feature command line wrapper
install_apt_package shellcheck # lint tool for shell scripts
install_apt_package shfmt # shell parser, formatter, and interpreter
install_apt_package stow # I use it to manage my dotfiles symlinks
install_apt_package tig # Text interface for Git repositories
install_apt_package tmux # terminal multiplexer
install_apt_package tree # displays an indented directory tree, in color
install_apt_package universal-ctags # builds text indexes for source code files
install_apt_package neovim # Vim-fork focused on extensibility and usability
install_apt_package vim # Vi IMproved - enhanced vi editor
install_apt_package wget # retrieves files from the web
install_apt_package xsel # command line tool to access X clipboard and selection buffers
install_apt_package zoxide # Shell extension to easily jump to frequently accessed directories

# Diagnostics
install_apt_package atop # Monitor for system resources and process activity
install_apt_package htop # interactive processes viewer
install_apt_package iftop # displays bandwidth usage information on an network interface
install_apt_package iotop # simple top-like I/O monitor
install_apt_package lsof # Utility to list open files
install_apt_package ltrace # Tracks runtime library calls in dynamically linked programs
install_apt_package nethogs # Net top tool grouping bandwidth per process
install_apt_package strace # System call tracer

# Packages (debian-specific):

install_apt_package fd-find # Simple, fast and user-friendly alternative to find
install_apt_package git-extras # Extra commands for git
install_apt_package silversearcher-ag # very fast grep-like program, alternative to ack-grep

if _has go; then
log_trace "Installing Go tools."
go install github.com/jesseduffield/lazygit # terminal ui for git
go install github.com/jesseduffield/lazydocker # terminal ui for docker and docker-compose
fi

log_trace "Installing non-packaged software."

# shellcheck shell=bash
# Starship: shell-agnostic prompt
if _has starship; then
  current_version=$(starship --version | head -n 1 | awk '{print $2}')
  latest_version=$(curl -s https://api.github.com/repos/starship/starship/releases/latest | jq ".tag_name" | tr -d 'v"')
  if [ "$current_version" != "$latest_version" ]; then
    log_trace "Starship's current version ($current_version) is different than latest ($latest_version). Installing it."
    install_starship=1
  else
    install_starship=0
  fi
else
  log_trace "Starship is not installed. Installing it."
  install_starship=1
fi

if [ "$install_starship" = "1" ]; then
  curl -sS https://starship.rs/install.sh | sudo sh -s -- --yes
fi

log_info "Configuring packages for Linux (Debian and derivative distros) done."
