#!/usr/bin/env bash
# DO NOT EDIT — generated by generate_distro_package_setup_code.sh
# Configuring minimal packages for a Linux system
set -uo pipefail

dotdir="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
source "$dotdir/setup/setup_functions.sh"

log_info "Configuring packages for Linux (Arch and derivative distros) ..."

log_trace "Upgrading existing packages."
sudo pacman -Syu --noconfirm

log_trace "Installing packages."

# Common
install_pacman_package bat
install_pacman_package curl
install_pacman_package eza
install_pacman_package git
install_pacman_package jq
install_pacman_package mosh
install_pacman_package ranger
install_pacman_package ripgrep
install_pacman_package tmux
install_pacman_package vim

# Diagnostics
install_pacman_package htop
install_pacman_package lsof
install_pacman_package strace

# arch-specific:

install_pacman_package fd

log_info "Configuring packages for Linux (Arch and derivative distros) done."
