#!/usr/bin/env bash
# DO NOT EDIT — generated by generate_distro_package_setup_code.sh
# Configuring minimal packages for a Linux system
set -euo pipefail

sudo pacman -Syu --noconfirm

# Minimal packages (distro-agnostic):

# Common
sudo pacman -S --noconfirm --needed bat
sudo pacman -S --noconfirm --needed curl
sudo pacman -S --noconfirm --needed eza
sudo pacman -S --noconfirm --needed git
sudo pacman -S --noconfirm --needed jq
sudo pacman -S --noconfirm --needed mosh
sudo pacman -S --noconfirm --needed ranger
sudo pacman -S --noconfirm --needed ripgrep
sudo pacman -S --noconfirm --needed tmux
sudo pacman -S --noconfirm --needed vim

# Diagnostics
sudo pacman -S --noconfirm --needed htop
sudo pacman -S --noconfirm --needed lsof
sudo pacman -S --noconfirm --needed strace

# Minimal packages (arch-specific):

sudo pacman -S --noconfirm --needed fd
