#!/usr/bin/env bash
# DO NOT EDIT — generated by generate_distro_package_setup_code.sh
# Configuring packages for a Linux system
set -uo pipefail

dotdir="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
source "$dotdir/setup/setup_functions.sh"

log_info "Configuring packages for Linux (Arch and derivative distros) ..."

log_info "Upgrading existing packages."
sudo pacman -Syu --noconfirm

log_info "Installing packages."

# Packages (distro-agnostic):

# Common
install_pacman_package bat # cat replacement with syntax highlighting, git integration
install_pacman_package cifs-utils # Common Internet File System utilities
install_pacman_package curl # command line tool for transferring data with URL syntax
install_pacman_package eza # Modern replacement for ls
install_pacman_package git # fast, scalable, distributed revision control system
install_pacman_package grc # Colorize logfiles and command output
install_pacman_package hexyl # Terminal hex viewer
install_pacman_package jq # lightweight and flexible command-line JSON processor
install_pacman_package lnav # ncurses-based log file viewer
install_pacman_package mosh # Mobile shell that supports roaming and intelligent local echo
install_pacman_package mtr # traceroute and ping in a single tool
install_pacman_package ncdu # NCurses Disk Usage
install_pacman_package ngrep # grep for network traffic
install_pacman_package ranger # caca-utils highlight atool w3m poppler-utils mediainfo # File manager with an ncurses frontend written in Python
install_pacman_package ripgrep # Fast regex text searching tool for files (recursively), respects .gitignore
install_pacman_package rlwrap # readline feature command line wrapper
install_pacman_package shellcheck # lint tool for shell scripts
install_pacman_package shfmt # shell parser, formatter, and interpreter
install_pacman_package stow # I use it to manage my dotfiles symlinks
install_pacman_package tig # Text interface for Git repositories
install_pacman_package tmux # terminal multiplexer
install_pacman_package tree # displays an indented directory tree, in color
install_pacman_package universal-ctags # builds text indexes for source code files
install_pacman_package neovim # Vim-fork focused on extensibility and usability
install_pacman_package vim # Vi IMproved - enhanced vi editor
install_pacman_package wget # retrieves files from the web
install_pacman_package xsel # command line tool to access X clipboard and selection buffers
install_pacman_package zoxide # Shell extension to easily jump to frequently accessed directories

# Diagnostics
install_pacman_package atop # Monitor for system resources and process activity
install_pacman_package htop # interactive processes viewer
install_pacman_package iftop # displays bandwidth usage information on an network interface
install_pacman_package iotop # simple top-like I/O monitor
install_pacman_package lsof # Utility to list open files
install_pacman_package ltrace # Tracks runtime library calls in dynamically linked programs
install_pacman_package nethogs # Net top tool grouping bandwidth per process
install_pacman_package strace # System call tracer

# Packages (arch-specific):

install_pacman_package fd # Simple, fast and user-friendly alternative to find
install_pacman_package git-delta # Syntax-highlighting pager for git and diff output
install_pacman_package lazydocker # terminal ui for docker and docker-compose
install_pacman_package lazygit # terminal ui for git
install_pacman_package starship # shell-agnostic prompt
install_pacman_package the_silver_searcher # very fast grep-like program, alternative to ack-grep
install_pacman_package uv # An extremely fast Python package installer and resolver written in Rust

log_info "Configuring packages for Linux (Arch and derivative distros) done."
