#!/usr/bin/env bash
# DO NOT EDIT — generated by generate_distro_package_setup_code.sh
# Configuring minimal packages for a Linux system
set -uo pipefail

dotdir="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
source "$dotdir/setup/setup_functions.sh"

log_info "Configuring packages for Linux (Debian and derivative distros) ..."

log_trace "Upgrading existing packages."
sudo apt-get update -y --fix-missing -qq && sudo apt-get upgrade -y -qq

log_trace "Installing packages."

# Common
install_apt_package bat
install_apt_package curl
install_apt_package eza
install_apt_package git
install_apt_package jq
install_apt_package mosh
install_apt_package ranger
install_apt_package ripgrep
install_apt_package tmux
install_apt_package vim

# Diagnostics
install_apt_package htop
install_apt_package lsof
install_apt_package strace

# debian-specific:

install_apt_package fd-find

log_info "Configuring packages for Linux (Debian and derivative distros) done."
