#!/usr/bin/env bash
# DO NOT EDIT — generated by generate_distro_package_setup_code.sh
# Configuring minimal packages for a Linux system
set -euo pipefail

sudo apt-get update -y --fix-missing -qq && sudo apt-get upgrade -y -qq

# Minimal packages (distro-agnostic):

# Common
sudo apt-get install -y -qq bat
sudo apt-get install -y -qq curl
sudo apt-get install -y -qq eza
sudo apt-get install -y -qq git
sudo apt-get install -y -qq jq
sudo apt-get install -y -qq mosh
sudo apt-get install -y -qq ranger
sudo apt-get install -y -qq ripgrep
sudo apt-get install -y -qq tmux
sudo apt-get install -y -qq vim

# Diagnostics
sudo apt-get install -y -qq htop
sudo apt-get install -y -qq lsof
sudo apt-get install -y -qq strace

# Minimal packages (debian-specific):

sudo apt-get install -y -qq fd-find
