#!/usr/bin/env bash
# Generate code for Linux (distro-specific) package setup

dotdir="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
source "$dotdir/setup/setup_functions.sh"

function append_source_file_lines_with_prefix_into_dest_file() {
  local src_file="$1"
  local dest_file="$2"
  local line_prefix="$3"

  if [ ! -f "$src_file" ]; then return; fi

  while IFS= read -r line; do
    if [[ "$line" =~ ^#.* ]]; then # Leave comments unchanged
      echo "$line" >>"$dest_file"
    elif [[ -z "${line// }" ]]; then # Skip blank lines
      echo "" >>"$dest_file"
    else
      echo "$line_prefix $line" >>"$dest_file"
    fi
  done <"$src_file"
}

function generate_for_distro() {
  local distro
  distro=$(echo "$1" | tr '[:upper:]' '[:lower:]')

  local os_description pm_update_system pm_install_package pm_aur_install_package
  if [ "$distro" = "debian" ]; then
    os_description="Linux (Debian and derivative distros)"
    pm_update_system='sudo apt-get update -y --fix-missing -qq && sudo apt-get upgrade -y -qq'
    pm_install_package='install_apt_package'

  elif [ "$distro" = "arch" ]; then
    os_description="Linux (Arch and derivative distros)"
    pm_update_system='sudo pacman -Syu --noconfirm'
    pm_install_package='install_pacman_package'
    pm_aur_install_package='install_yay_package'

  else
    log_error "generate_distro_package_setup_code: unknown Linux distro: $distro"
    return 1
  fi

  local setup_dir setup_file src_file
  setup_dir="$(cd "$(dirname "$0")" && pwd)"
  setup_file="$setup_dir/configure_packages_$distro.sh"

  rm -f "$setup_file"
  touch "$setup_file"
  chmod 755 "$setup_file"

  echo \
    '#!/usr/bin/env bash
# DO NOT EDIT — generated by generate_distro_package_setup_code.sh
# Configuring packages for a Linux system
set -uo pipefail

dotdir="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
source "$dotdir/setup/setup_functions.sh"
' >>"$setup_file"

  echo "log_info \"Configuring packages for ${os_description} ...\"" >>"$setup_file"

  echo -e '\nlog_info "Upgrading existing packages."' >>"$setup_file"
  echo -e "$pm_update_system" >>"$setup_file"

  echo -e '\nlog_info "Installing packages."' >>"$setup_file"

  # Package manager

  src_file="$setup_dir/packages_pm_common_1.txt"
  if [ -f "$src_file" ]; then
    echo -e '\n# Packages (distro-agnostic):\n' >>"$setup_file"
    append_source_file_lines_with_prefix_into_dest_file "$src_file" "$setup_file" "$pm_install_package"
  fi

  src_file="$setup_dir/packages_pm_${distro}_1.txt"
  if [ -f "$src_file" ]; then
    echo -e "\n# Packages ($distro-specific):\n" >>"$setup_file"
    append_source_file_lines_with_prefix_into_dest_file "$src_file" "$setup_file" "$pm_install_package"
  fi

  # AUR

  src_file="$setup_dir/packages_pm_aur_1.txt"
  if [ "$distro" = "arch" ] && [ -f "$src_file" ]; then
    echo -e '\nlog_trace "Installing AUR packages."' >>"$setup_file"
    append_source_file_lines_with_prefix_into_dest_file "$src_file" "$setup_file" "$pm_aur_install_package"
  fi

  # Go-lang

  src_file="$setup_dir/packages_go_${distro}_1.txt"
  if [ -f "$src_file" ]; then
    echo -e '\nif _has go; then' >>"$setup_file"
    echo -e 'log_trace "Installing Go tools."' >>"$setup_file"
    append_source_file_lines_with_prefix_into_dest_file "$src_file" "$setup_file" "go install"
    echo 'fi' >>"$setup_file"
  fi

  # Manual install

  src_file="$setup_dir/packages_shell_common_1.sh"
  if [ -f "$src_file" ]; then
    echo -e '\nlog_trace "Installing non-packaged software."\n' >>"$setup_file"
    cat "$src_file" >>"$setup_file"
  fi

  src_file="$setup_dir/packages_shell_${distro}_1.sh"
  if [ -f "$src_file" ]; then
    echo -e '\nlog_trace "Installing non-packaged software."\n' >>"$setup_file"
    cat "$src_file" >>"$setup_file"
  fi

  echo -e "\nlog_info \"Configuring packages for ${os_description} done.\"" >>"$setup_file"
}

function generate_minimal_for_distro() {
  local distro
  distro=$(echo "$1" | tr '[:upper:]' '[:lower:]')

  local os_description pm_update_system pm_install_package
  if [ "$distro" = "debian" ]; then
    os_description="Linux (Debian and derivative distros)"
    pm_update_system='sudo apt-get update -y --fix-missing -qq && sudo apt-get upgrade -y -qq'
    pm_install_package='install_apt_package'

  elif [ "$distro" = "arch" ]; then
    os_description="Linux (Arch and derivative distros)"
    pm_update_system='sudo pacman -Syu --noconfirm'
    pm_install_package='install_pacman_package'

  else
    log_error "generate_distro_package_setup_code: unknown Linux distro: $distro"
    return 1
  fi

  local setup_dir setup_file src_file
  setup_dir="$(cd "$(dirname "$0")" && pwd)"
  setup_file="$setup_dir/configure_packages_minimal_$distro.sh"

  # Only generate if any minimal source files exist for this distro
  local has_minimal_src=0
  for f in "$setup_dir"/packages_pm_minimal_1.txt "$setup_dir/packages_pm_minimal_${distro}_1.txt"; do
    [ -f "$f" ] && has_minimal_src=1
  done
  if [ "$has_minimal_src" -eq 0 ]; then
    return 0
  fi

  rm -f "$setup_file"
  touch "$setup_file"
  chmod 755 "$setup_file"

  echo \
    '#!/usr/bin/env bash
# DO NOT EDIT — generated by generate_distro_package_setup_code.sh
# Configuring minimal packages for a Linux system
set -uo pipefail

dotdir="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
source "$dotdir/setup/setup_functions.sh"
' >>"$setup_file"

  echo "log_info \"Configuring packages for ${os_description} ...\"" >>"$setup_file"

  echo -e '\nlog_trace "Upgrading existing packages."' >>"$setup_file"
  echo -e "$pm_update_system" >>"$setup_file"

  src_file="$setup_dir/packages_pm_minimal_1.txt"
  if [ -f "$src_file" ]; then
    echo -e '\nlog_trace "Installing packages."\n' >>"$setup_file"
    append_source_file_lines_with_prefix_into_dest_file "$src_file" "$setup_file" "$pm_install_package"
  fi

  src_file="$setup_dir/packages_pm_minimal_${distro}_1.txt"
  if [ -f "$src_file" ]; then
    echo -e "\n# ${distro}-specific:\n" >>"$setup_file"
    append_source_file_lines_with_prefix_into_dest_file "$src_file" "$setup_file" "$pm_install_package"
  fi

  echo -e "\nlog_info \"Configuring packages for ${os_description} done.\"" >>"$setup_file"
}

# ── Entry point ────────────────────────────────────────────────────────────────

distro="${1:-}"

if [ -z "$distro" ]; then
  generate_for_distro debian && generate_for_distro arch
  generate_minimal_for_distro debian && generate_minimal_for_distro arch
else
  generate_for_distro "$distro"
fi
